export const theme = {
  primary: '#FF6B6B',
  primaryLight: '#FF8E8E',
  primaryDim: '#CC5555',
  secondary: '#4ECDC4',
  secondaryLight: '#6EE7DE',
  secondaryDim: '#3BA99E',
  accent: '#FFE66D',
  accentDim: '#CCB847',
  success: '#00B894',
  successDim: '#00A080',
  warning: '#FDCB6E',
  error: '#FF6B6B',
  info: '#74B9FF',
  purple: '#A29BFE',
  purpleDim: '#7C6FE0',
  surface: '#1A1A2E',
  surfaceAlt: '#16213E',
  surfaceBorder: '#2D3436',
  surfaceBorderLight: '#3D4A5C',
  text: '#DFE6E9',
  textBright: '#FFFFFF',
  textDim: '#636E72',
  background: '#0D1117',
};

export const STATUS_COLORS: Record<string, string> = {
  idle: theme.textDim,
  running: theme.secondary,
  waiting: theme.warning,
  failed: theme.error,
  completed: theme.success,
  blocked: theme.error,
  pending: theme.textDim,
  planning: theme.purple,
  review: theme.info,
  testing: theme.accent,
  cancelled: theme.textDim,
};

export const STATUS_ICONS: Record<string, string> = {
  idle: '○',
  running: '●',
  waiting: '⏳',
  failed: '✗',
  completed: '✓',
  blocked: '⊘',
  pending: '○',
  planning: '◎',
  review: '👁',
  testing: '⚡',
  cancelled: '⊘',
};
